apiVersion: v2
name: rad-plugins
version: 2.3.36
description: A Helm chart to run the RAD Security plugins
home: https://rad.security
icon: https://app.rad.security/apple-touch-icon-180x180.png
keywords:
  - security
  - rad
  - runtime
  - kubernetes
  - helm
maintainers:
  - name: RAD Security Engineering
    email: infrastructure@rad.security
annotations:
  artifacthub.io/category: security
  # Possible kind options are added, changed, deprecated, removed, fixed and security.
  artifacthub.io/changes: |
    - kind: changed
      description: Improved collection of metrics and heartbeats for all plugins.
    - kind: added
      description: Added reverse DNS lookup to fill hostnames when tracing Network Connections in rad-runtime.
    - kind: fixed
      description: Added fsGroup to enable write to ephemeral storage. Updated dependencies to fix vulnerabilities.
    - kind: fixed
      description: Fixed cross-region ECR scanning in rad-sbom.
    - kind: added
      description: Added configuration to rad-sbom allowing to ignore specific repositories or images.
    - kind: security
      description: Updated dependencies to remove vulnerabilities in all plugins.
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/links: |
    - name: source
      url: https://github.com/rad-security/plugins-helm-chart
    - name: support
      url: https://github.com/rad-security/plugins-helm-chart/issues
