apiVersion: v2
name: rad-plugins
version: 2.0.1
description: A Helm chart to run the RAD Security plugins
home: https://rad.security
icon: https://rad.security/hs-fs/hubfs/Supplementary%20COMBO@2x.png?width=655&height=229&name=Supplementary%20COMBO@2x.png
keywords:
  - security
  - rad
  - runtime
  - kubernetes
  - helm
maintainers:
  - name: RAD Security Engineering
    email: infrastructure@rad.security
annotations:
  artifacthub.io/category: security
  # Possible kind options are added, changed, deprecated, removed, fixed and security.
  artifacthub.io/changes: |
    - kind: added
      description: Add experimental support for OpenShift and cri-o
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: source
      url: https://github.com/rad-security/plugins-helm-chart
    - name: support
      url: https://github.com/rad-security/plugins-helm-chart/issues
