{{ if and (not (or .Values.rad.accessKeySecretNameOverride)) (or (and .Values.rad.base64AccessKeyId .Values.rad.base64SecretKey) .Values.rad.apiKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: rad-access-key
  namespace: {{ .Release.Namespace }}
  labels:
    maintained_by: rad-security
data:
  access-key-id: {{ if .Values.rad.base64AccessKeyId }}{{ .Values.rad.base64AccessKeyId }}{{ else }}{{ (split ":" .Values.rad.apiKey)._0 }}{{- end }}
  secret-key: {{ if .Values.rad.base64SecretKey }}{{ .Values.rad.base64SecretKey }}{{ else }}{{ (split ":" .Values.rad.apiKey)._1 }}{{- end }}
{{ end }}
