{{- if and .Values.openshift .Values.openshift.enabled -}}
{{- if .Values.runtime.enabled }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: rad-runtime-scc
allowHostDirVolumePlugin: true
allowHostPID: true
allowedCapabilities:
  - SYS_ADMIN
  - SYSLOG
  - SYS_PTRACE
  - SYS_RESOURCE
  - IPC_LOCK
  - NET_ADMIN
  - NET_RAW
readOnlyRootFilesystem: true
runAsUser:
  type: RunAsAny
priority: 0
seccompProfiles:
  - "*"
seLinuxContext:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Release.Namespace }}:rad-runtime
volumes:
  - "*"
{{- end }}

---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: rad-shared-scc
readOnlyRootFilesystem: true
priority: 1
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 65534
  uidRangeMax: 65534
requiredDropCapabilities:
  - ALL
seccompProfiles:
  - "*"
seLinuxContext:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Release.Namespace }}:rad-guard
  - system:serviceaccount:{{ .Release.Namespace }}:rad-sbom
  - system:serviceaccount:{{ .Release.Namespace }}:rad-sync
  - system:serviceaccount:{{ .Release.Namespace }}:rad-watch
volumes:
  - "*"

---

{{- end -}}
