{{- if .Values.watch.enabled -}}
{{- if eq (include "rad-plugins.deployInReleaseNamespace" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rad-watch
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-watch
    app_version: {{ .Values.watch.image.tag | quote }}
    maintained_by: rad.security
  {{- with .Values.watch.serviceAccountAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: rad-watch-api-token-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-watch
    app_version: {{ .Values.watch.image.tag | quote }}
    maintained_by: rad.security
  annotations:
    kubernetes.io/service-account.name: rad-watch
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rad-watch-configmap-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-watch
    app_version: {{ .Values.watch.image.tag | quote }}
    maintained_by: rad.security
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: [ "rad-watch-dynamic-configuration", "rad-watch-custom-resource-rules" ]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rad-watch-configmap-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-watch
    app_version: {{ .Values.watch.image.tag | quote }}
    maintained_by: rad.security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rad-watch-configmap-reader
subjects:
  - kind: ServiceAccount
    name: rad-watch
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rad-watch-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-watch
    app_version: {{ .Values.watch.image.tag | quote }}
    maintained_by: rad.security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rad-leader-election-role
subjects:
  - kind: ServiceAccount
    name: rad-watch
    namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rad-watch
  labels:
    app_name: rad-watch
    app_version: {{ .Values.watch.image.tag | quote }}
    maintained_by: rad.security
rules:
  - apiGroups: [""]
    resources: ["configmaps", "namespaces", "nodes", "pods", "services", "serviceaccounts"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: [ "daemonsets", "deployments", "replicasets", "statefulsets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "batch" ]
    resources: [ "cronjobs", "jobs" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "networking.k8s.io", "extensions" ]
    resources: [ "networkpolicies", "ingresses" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "ksoc.com" ]
    resources: [ "guardpolicies", "guardresults" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "get", "list", "watch" ]
---
{{- if eq (include "rad-plugins.deployInReleaseNamespace" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rad-watch
  labels:
    app_name: rad-watch
    app_version: {{ .Values.watch.image.tag | quote }}
    maintained_by: rad.security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rad-watch
subjects:
  - kind: ServiceAccount
    name: rad-watch
    namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if and ( eq .Values.eksAddon.enabled false ) ( eq (include "rad-plugins.deployInKubeSystem" .) "true" ) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rad-watch-kube-root-ca-reader
  namespace: kube-system
  labels:
    app_name: rad-watch
    maintained_by: rad.security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rad-kube-root-ca-reader
subjects:
  - kind: ServiceAccount
    name: rad-watch
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
