apiVersion: v1
kind: ConfigMap
metadata:
  name: rad-sbom-dynamic-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-sbom
    app_version: {{ .Values.sbom.image.tag | quote }}
    maintained_by: rad.security
data:
# Placeholder for dynamic configuration created via rad-sync
# Main purpose of this ConfigMap is to delete it when rad-plugins helm chart is uninstalled
