{{- if .Values.sbom.enabled -}}
{{- if eq (include "rad-plugins.deployInReleaseNamespace" .) "true" -}}
apiVersion: v1
kind: Service
metadata:
  name:  rad-sbom
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-sbom
    app_version: {{ .Values.sbom.image.tag | quote }}
    maintained_by: rad.security
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app_name: rad-sbom
    app_version: {{ .Values.sbom.image.tag | quote }}
    maintained_by: rad.security
{{- end -}}
{{- end -}}
