{{- if and .Values.runtime .Values.runtime.enabled -}}
{{- $openshiftEnabled := and .Values.openshift .Values.openshift.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: rad-high-priority
  labels:
    maintained_by: rad.security
value: 1000000
globalDefault: false
description: "Priority class used by rad-runtime."

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rad-runtime
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-runtime
    app_version: {{ .Values.runtime.agent.image.tag | quote }}
    maintained_by: rad.security
spec:
  selector:
    matchLabels:
      app_name: rad-runtime
  updateStrategy:
{{ toYaml .Values.runtime.updateStrategy | indent 4 }}
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/agent: unconfined
        prometheus.io/path: "/"
        prometheus.io/scrape: "true"
      labels:
        app_name: rad-runtime
        app_version: {{ .Values.runtime.agent.image.tag | quote }}
        maintained_by: rad.security
    spec:
      {{- if .Values.workloads.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.workloads.imagePullSecretName }}
      {{- end }}
      # hostPID is enabled by default when running on openshift
      hostPID: {{ (quote .Values.runtime.agent.hostPID | empty) | ternary $openshiftEnabled .Values.runtime.agent.hostPID }}
      initContainers:
{{ include "rad-plugins.bootstrap-initcontainer" . | indent 8 }}
      containers:
        - env:
            - name: AGENT_VERSION
              value: {{ .Values.runtime.agent.image.tag | quote }}
            - name: CHART_VERSION
              value: {{ .Chart.Version }}
            - name: API_URL
              value: {{ .Values.rad.apiUrl }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            {{- if .Values.rad.awsSecretId }}
            - name: RAD_AWS_SECRET_ID
              value: {{ .Values.rad.awsSecretId }}
            {{- else }}
{{ include "rad-plugins.access-key-env-secret" . | indent 12 }}
            {{- end }}
            - name: HOST_ROOT
              value: /host
            {{- with .Values.runtime.agent.collectors }}
            # containerd is enabled by default unless running on OpenShift.
            - name: TRACER_COLLECTOR_CONTAINERD_ENABLED
              value: {{ (quote .containerd.enabled | empty) | ternary (not $openshiftEnabled) .containerd.enabled | quote }}
            - name: TRACER_COLLECTOR_CONTAINERD_SOCKET
              value: {{ .containerd.socket | quote }}
            # crio is enabled by default when running on OpenShift.
            - name: TRACER_COLLECTOR_CRIO_ENABLED
              value: {{ (quote .crio.enabled | empty) | ternary $openshiftEnabled .crio.enabled | quote}}
            - name: TRACER_COLLECTOR_CRIO_SOCKET
              value: {{ .crio.socket | quote }}
            - name: TRACER_COLLECTOR_DOCKER_ENABLED
              value: {{ .docker.enabled | quote }}
            - name: TRACER_COLLECTOR_DOCKER_SOCKET
              value: {{ .docker.socket | quote }}
            {{- if .runtimePath }}
            - name: RUNTIME_PATH
              value: {{ .runtimePath | quote }}
            {{- end }}
            {{- end }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: TRACER_AUTO_MOUNT_FILESYSTEMS
              value: "1"
            - name: TRACER_NET_IGNORE_HOST_NETWORK_NS
              value: "true"
            {{- if .Values.runtime.reachableVulnerabilitiesEnabled }}
            - name: TRACER_OPEN_ENABLED
              value: "true"
            - name: TRACER_OPEN_PREFIXES
              value: "/lib,/lib64,/usr,/bin,/sbin"
            {{- end }}
            {{- if .Values.runtime.agent.eventQueueSize }}
            - name: EVENT_QUEUE_SIZE
              value: {{ .Values.runtime.agent.eventQueueSize | quote }}
            {{- end }}
            {{- if .Values.runtime.agent.grpcServerBatchSize }}
            - name: GRPC_SERVER_BATCH_SIZE
              value: {{ .Values.runtime.agent.grpcServerBatchSize | quote }}
            {{- end }}
            {{- range $key, $value := .Values.runtime.agent.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          image: {{ .Values.runtime.agent.image.repository }}:{{ .Values.runtime.agent.image.tag }}
          imagePullPolicy: Always
          name: agent
          ports:
            - containerPort: 8000
          resources:
{{ toYaml .Values.runtime.agent.resources | indent 12 }}
          securityContext:
            appArmorProfile:
              type: Unconfined
            capabilities:
              add:
                - SYS_ADMIN
                - SYSLOG
                - SYS_PTRACE
                - SYS_RESOURCE
                - IPC_LOCK
                - NET_ADMIN
                - NET_RAW
              drop:
                - ALL
            privileged: false
            runAsUser: 0
            seLinuxOptions:
              type: super_t
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: api-token
              readOnly: true
            - mountPath: /tmp
              name: unix-socket
            - mountPath: /host/bin
              name: bin
              readOnly: true
            - mountPath: /host/etc
              name: etc
            - mountPath: /host/opt
              name: opt
            - mountPath: /host/usr
              name: usr
              readOnly: true
            - mountPath: /host/run
              name: run
              readOnly: true
            - mountPath: /host/proc
              name: proc
              readOnly: true
            - mountPath: /run
              name: run
            - mountPath: /sys/kernel/debug
              name: debugfs
            - mountPath: /sys/kernel/tracing
              name: tracefs
            - mountPath: /sys/fs/cgroup
              name: cgroup
            - mountPath: /sys/fs/bpf
              name: bpffs
            {{- with .Values.runtime.agent.mounts.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        - env:
            - name: AGENT_VERSION
              value: {{ .Values.runtime.agent.image.tag | quote }}
            - name: CHART_VERSION
              value: {{ .Chart.Version }}
            - name: API_URL
              value: {{ .Values.rad.apiUrl }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            {{- if .Values.rad.awsSecretId }}
            - name: RAD_AWS_SECRET_ID
              value: {{ .Values.rad.awsSecretId }}
            {{- else }}
{{ include "rad-plugins.access-key-env-secret" . | indent 12 }}
            {{- end }}
            - name: STDOUT_ENABLED
              value: "false"
            - name: RAD_API_ENABLED
              value: "true"
            {{ if .Values.runtime.exporter.execFilters -}}
            {{- $filters := printf "execFilters: %s" (.Values.runtime.exporter.execFilters | toJson ) -}}
            - name: EXEC_FILTERS
              value: {{  $filters | fromYaml | toJson | squote }}
            {{- end }}
            {{- range $key, $value := .Values.runtime.exporter.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          image: {{ .Values.runtime.exporter.image.repository }}:{{ .Values.runtime.exporter.image.tag }}
          imagePullPolicy: Always
          name: exporter
          ports:
            - containerPort: 8001
          resources:
{{ toYaml .Values.runtime.exporter.resources | indent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: unix-socket
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: api-token
              readOnly: true
      dnsPolicy: ClusterFirst
      {{ if .Values.runtime.nodeName -}}
      nodeName: {{ .Values.runtime.nodeName }}
      {{ end -}}
      {{- with .Values.runtime.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
        {{- end }}
      priorityClassName: rad-high-priority
      restartPolicy: Always
      automountServiceAccountToken: false
      serviceAccountName: rad-runtime
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      {{- with .Values.runtime.tolerations }}
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
        - name: api-token
          secret:
            secretName: rad-runtime-api-token-secret
        - name: unix-socket
        - hostPath:
            path: /bin
            type: ""
          name: bin
        - hostPath:
            path: /etc
            type: ""
          name: etc
        - hostPath:
            path: /opt
            type: ""
          name: opt
        - hostPath:
            path: /usr
            type: ""
          name: usr
        - hostPath:
            path: /proc
            type: ""
          name: proc
        - hostPath:
            path: /run
            type: ""
          name: run
        - hostPath:
            path: /sys/fs/cgroup
            type: ""
          name: cgroup
        - hostPath:
            path: /sys/fs/bpf
            type: ""
          name: bpffs
        - hostPath:
            path: /sys/kernel/debug
            type: ""
          name: debugfs
        - hostPath:
            path: /sys/kernel/tracing
            type: ""
          name: tracefs
        {{- with .Values.runtime.agent.mounts.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end -}}
