apiVersion: v1
kind: ConfigMap
metadata:
  name: rad-runtime-dynamic-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-runtime
    app_version: {{ .Values.runtime.image.tag | quote }}
    maintained_by: rad.security
data:
# Placeholder for dynamic configuration

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rad-runtime-exporter-dynamic-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-runtime
    app_version: {{ .Values.runtime.image.tag | quote }}
    maintained_by: rad.security
data:
# Placeholder for dynamic configuration
