{{- if and .Values.runtime .Values.runtime.enabled -}}
{{- if eq (include "rad-plugins.deployResources" .) "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rad-runtime-dynamic-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-runtime
    app_version: {{ .Values.runtime.agent.image.tag | quote }}
    maintained_by: rad.security
data: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rad-runtime-exporter-dynamic-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-runtime
    app_version: {{ .Values.runtime.agent.image.tag | quote }}
    maintained_by: rad.security
data: {}
{{- end }}
{{- end }}
