{{- if and .Values.runtime .Values.runtime.enabled -}}
{{- if .Values.runtime.httpTracingEnabled }}
{{- if and .Values.runtime.piiAnalyzer .Values.runtime.piiAnalyzer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rad-pii-analyzer
  namespace: {{ .Release.Namespace }}
  labels:
    app: rad-pii-analyzer
spec:
  replicas: {{ default 1 .Values.runtime.piiAnalyzer.replicas }}
  selector:
    matchLabels:
      app: rad-pii-analyzer
  template:
    metadata:
      labels:
        app: rad-pii-analyzer
{{- if and .Values.runtime .Values.runtime.piiAnalyzer .Values.runtime.piiAnalyzer.image .Values.runtime.piiAnalyzer.image.tag }}
        app_version: {{ default "2.2.4" .Values.runtime.piiAnalyzer.image.tag | quote }}
{{- else }}
        app_version: "2.2.4"
{{- end }}
    spec:
      containers:
      - name: rad-pii-analyzer
{{- if and .Values.runtime .Values.runtime.piiAnalyzer .Values.runtime.piiAnalyzer.image }}
        image: {{ default "mcr.microsoft.com/presidio-analyzer" .Values.runtime.piiAnalyzer.image.repository }}:{{ default "2.2.4" .Values.runtime.piiAnalyzer.image.tag }}
{{- else }}
        image: mcr.microsoft.com/presidio-analyzer:2.2.4
{{- end }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
{{- if and .Values.runtime .Values.runtime.piiAnalyzer .Values.runtime.piiAnalyzer.resources }}
        resources:
          requests:
            memory: {{ default "128Mi" .Values.runtime.piiAnalyzer.resources.requests.memory }}
            cpu: {{ default "100m" .Values.runtime.piiAnalyzer.resources.requests.cpu }}
          limits:
            memory: {{ default "2Gi" .Values.runtime.piiAnalyzer.resources.limits.memory }}
            cpu: {{ default "1000m" .Values.runtime.piiAnalyzer.resources.limits.cpu }}
{{- else }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
{{- end }}
        env:
          - name: PORT
            value: "8080"
{{- with .Values.runtime.piiAnalyzer.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: rad-pii-analyzer
  namespace: rad
  labels:
    app: rad-pii-analyzer
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: rad-pii-analyzer
  selector:
    app: rad-pii-analyzer
{{- end -}}
{{- end -}}
{{- end -}}
