{{- if and .Values.runtime .Values.runtime.enabled -}}
{{- if .Values.runtime.httpTracingEnabled }}
{{- if and .Values.runtime.piiAnalyzer .Values.runtime.piiAnalyzer.enabled -}}

{{- if eq (include "rad-plugins.deployRbac" .) "true" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rad-pii-analyzer
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: rad-pii-analyzer
    app_version: {{ .Values.runtime.piiAnalyzer.image.tag | quote }}
    maintained_by: rad.security
  {{- with .Values.runtime.piiAnalyzer.serviceAccountAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
{{- end }}

{{- if eq (include "rad-plugins.deployResources" .) "true" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rad-pii-analyzer
  namespace: {{ .Release.Namespace }}
  labels:
    app: rad-pii-analyzer
spec:
  replicas: {{ .Values.runtime.piiAnalyzer.replicas }}
  selector:
    matchLabels:
      app: rad-pii-analyzer
  template:
    metadata:
      labels:
        app: rad-pii-analyzer
        app_version: {{ .Values.runtime.piiAnalyzer.image.tag | quote }}
    spec:
      serviceAccountName: rad-pii-analyzer
      automountServiceAccountToken: false
      securityContext:
      {{- if .Values.rad.seccompProfile.enabled }}
        seccompProfile:
          type: RuntimeDefault
      {{- end }}
      containers:
      - name: rad-pii-analyzer
        image: {{ .Values.runtime.piiAnalyzer.image.repository }}:{{ .Values.runtime.piiAnalyzer.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ .Values.runtime.piiAnalyzer.resources.requests.memory }}
            cpu: {{ .Values.runtime.piiAnalyzer.resources.requests.cpu }}
          limits:
            memory: {{ .Values.runtime.piiAnalyzer.resources.limits.memory }}
            cpu: {{ .Values.runtime.piiAnalyzer.resources.limits.cpu }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
      {{- if .Values.rad.seccompProfile.enabled }}
        seccompProfile:
          type: RuntimeDefault
      {{- end }}
        env:
          - name: PORT
            value: "8080"
          {{- range $key, $value := .Values.runtime.piiAnalyzer.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
{{- with .Values.runtime.piiAnalyzer.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.runtime.piiAnalyzer.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: rad-pii-analyzer
  namespace: rad
  labels:
    app: rad-pii-analyzer
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: rad-pii-analyzer
  selector:
    app: rad-pii-analyzer
{{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
