name: sync

on:
  push:
    branches:
      - 'main'

jobs:
  cloudflare-registry:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: install Helm
        uses: azure/setup-helm@v3
      - name: sync registry
        run: make sync-repo-cloudflare
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
