name: Test RBAC/Resources Separation

on:
  push:
    branches: [ main ]
    paths:
      - 'stable/rad-plugins/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'stable/rad-plugins/**'
  workflow_dispatch:

jobs:
  test-separation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Create test directories
        run: |
          mkdir -p test-output-{default,no-rbac,no-resources,pii,pii-no-rbac,pii-no-resources}

      - name: Test default (both RBAC and resources)
        run: |
          helm template stable/rad-plugins \
            --set runtime.enabled=true \
            --output-dir test-output-default
          echo "Default configuration file count: $(find test-output-default -type f | wc -l)"
          # Verify both RBAC and non-RBAC resources
          if ! grep -q "kind: ClusterRole\|kind: Role\|kind: RoleBinding\|kind: ClusterRoleBinding\|kind: ServiceAccount" test-output-default/rad-plugins/templates/rbac.yaml; then
            echo "❌ Default configuration missing RBAC resources"
            exit 1
          fi
          if ! grep -q "kind: Deployment" test-output-default/rad-plugins/templates/guard/deployment.yaml; then
            echo "❌ Default configuration missing non-RBAC resources"
            exit 1
          fi
          echo "✅ Default configuration test passed"

      - name: Test no RBAC
        run: |
          helm template stable/rad-plugins \
            --set runtime.enabled=true \
            --set rad.deployment.rbac=false \
            --output-dir test-output-no-rbac
          echo "No RBAC configuration file count: $(find test-output-no-rbac -type f | wc -l)"
          # Verify RBAC resources are not present
          if [ -f test-output-no-rbac/rad-plugins/templates/rbac.yaml ]; then
            echo "❌ No RBAC configuration still has RBAC resources"
            exit 1
          fi
          # Verify non-RBAC resources are present
          if ! grep -q "kind: Deployment" test-output-no-rbac/rad-plugins/templates/guard/deployment.yaml; then
            echo "❌ No RBAC configuration missing non-RBAC resources"
            exit 1
          fi
          echo "✅ No RBAC configuration test passed"

      - name: Test no resources
        run: |
          helm template stable/rad-plugins \
            --set runtime.enabled=true \
            --set rad.deployment.resources=false \
            --output-dir test-output-no-resources
          echo "No resources configuration file count: $(find test-output-no-resources -type f | wc -l)"
          # Verify RBAC resources are present
          if ! grep -q "kind: ClusterRole\|kind: Role\|kind: RoleBinding\|kind: ClusterRoleBinding\|kind: ServiceAccount" test-output-no-resources/rad-plugins/templates/rbac.yaml; then
            echo "❌ No resources configuration missing RBAC resources"
            exit 1
          fi
          # Verify non-RBAC resources are not present
          if [ -f test-output-no-resources/rad-plugins/templates/guard/deployment.yaml ]; then
            echo "❌ No resources configuration still has non-RBAC resources"
            exit 1
          fi
          echo "✅ No resources configuration test passed"

      - name: Test PII Analyzer (both RBAC and resources)
        run: |
          helm template stable/rad-plugins \
            --set runtime.enabled=true \
            --set runtime.httpTracingEnabled=true \
            --set runtime.piiAnalyzer.enabled=true \
            --output-dir test-output-pii
          # Check if PII analyzer files exist
          if [ ! -f test-output-pii/rad-plugins/templates/runtime/pii-analyzer-deployment.yaml ]; then
            echo "❌ PII analyzer not rendered"
            exit 1
          fi
          # Verify both RBAC and non-RBAC components are in the file
          if ! grep -q "kind: ServiceAccount" test-output-pii/rad-plugins/templates/runtime/pii-analyzer-deployment.yaml; then
            echo "❌ PII analyzer missing RBAC resources"
            exit 1
          fi
          if ! grep -q "kind: Deployment" test-output-pii/rad-plugins/templates/runtime/pii-analyzer-deployment.yaml; then
            echo "❌ PII analyzer missing non-RBAC resources"
            exit 1
          fi
          echo "✅ PII analyzer test passed"

      - name: Test PII Analyzer (no RBAC)
        run: |
          helm template stable/rad-plugins \
            --set runtime.enabled=true \
            --set runtime.httpTracingEnabled=true \
            --set runtime.piiAnalyzer.enabled=true \
            --set rad.deployment.rbac=false \
            --output-dir test-output-pii-no-rbac
          # Check if PII analyzer file exists
          if [ ! -f test-output-pii-no-rbac/rad-plugins/templates/runtime/pii-analyzer-deployment.yaml ]; then
            echo "❌ PII analyzer not rendered"
            exit 1
          fi
          # Verify only non-RBAC components are in the file
          if grep -q "kind: ServiceAccount" test-output-pii-no-rbac/rad-plugins/templates/runtime/pii-analyzer-deployment.yaml; then
            echo "❌ PII analyzer with RBAC disabled still has ServiceAccount"
            exit 1
          fi
          if ! grep -q "kind: Deployment" test-output-pii-no-rbac/rad-plugins/templates/runtime/pii-analyzer-deployment.yaml; then
            echo "❌ PII analyzer with RBAC disabled missing non-RBAC resources"
            exit 1
          fi
          echo "✅ PII analyzer (no RBAC) test passed"

      - name: Test PII Analyzer (no resources)
        run: |
          helm template stable/rad-plugins \
            --set runtime.enabled=true \
            --set runtime.httpTracingEnabled=true \
            --set runtime.piiAnalyzer.enabled=true \
            --set rad.deployment.resources=false \
            --output-dir test-output-pii-no-resources
          # Check if PII analyzer file exists
          if [ ! -f test-output-pii-no-resources/rad-plugins/templates/runtime/pii-analyzer-deployment.yaml ]; then
            echo "❌ PII analyzer not rendered"
            exit 1
          fi
          # Verify only RBAC components are in the file
          if ! grep -q "kind: ServiceAccount" test-output-pii-no-resources/rad-plugins/templates/runtime/pii-analyzer-deployment.yaml; then
            echo "❌ PII analyzer with resources disabled missing ServiceAccount"
            exit 1
          fi
          if grep -q "kind: Deployment" test-output-pii-no-resources/rad-plugins/templates/runtime/pii-analyzer-deployment.yaml; then
            echo "❌ PII analyzer with resources disabled still has non-RBAC resources"
            exit 1
          fi
          echo "✅ PII analyzer (no resources) test passed"

      - name: Report success
        if: success()
        run: |
          echo "All RBAC/resources separation tests passed successfully!"
